### ISSUE TITLE
Please add Matter contact sensor

### ISSUE THREAD

**Issue by OABsoftware** [SiliconLabs/arduino#16]
Could a contact sensor be added to the Matter library?
A contact sensor can trigger push notifications, which can be very useful in some scenario's.

**Comment by lboue** [comment]
@OABsoftware I started here: https://github.com/lboue/arduino-1/commits/contact/

You can go ahead and create a PR.

**Comment by silabs-bozont** [comment]
Hello OABsoftware,
Thanks for the suggestion, it's on our radar and most likely will be coming in the next release!

**Comment by silabs-bozont** [comment]
Here's a little leak from the next release:
<img src="https://github.com/SiliconLabs/arduino/assets/124884281/edf98d29-6354-47ce-8b13-845bb0a5f13c" width="300"/>

**Comment by silabs-bozont** [comment]
It's now available in 2.0.0
