### ISSUE TITLE
Please Add Door Lock (0x000A)

### ISSUE THREAD

**Issue by ruddycanuck** [SiliconLabs/arduino#17]
I am designing a latch style lock for my shed and I would like to use Arduino / Matter. I think this is a cool use of Matter / Matter over Thread if possible. There is a door lock example in connectedhomeip 
/connectedhomeip/examples/lock-app/

Minimal Viable Product:
ID: 0x000A
setLockState : Lock/Unlock
getDoorState: Door Open/Closed
readBattLevel: Battery Level
Tamper Alert

Secondary (Complex) Phases
Keypad 
RFID
Users

**Comment by silabs-bozont** [comment]
Hello ruddycanuck,
_Matter Door Lock_ along with a few new devices is on our roadmap, so it will be available in one of the upcoming releases! Hang tight!

**Comment by Callum6677** [comment]
> Hello ruddycanuck, _Matter Door Lock_ along with a few new devices is on our roadmap, so it will be available in one of the upcoming releases! Hang tight!

Is there any public version of this roadmap that can be shared (sanitised if need be, timelines not essential because I know myself how unrealistic it can be to give them). I have a few things I was interested in that aren't yet possible, but don't want to waste your time cluttering GitHub issues with things you already have planned

**Comment by silabs-bozont** [comment]
Hi Callum6677,
I'll try to put something together on our goals, but feel free to ask!

**Comment by lboue** [comment]
Not included in [Release 2.0.0](https://github.com/SiliconLabs/arduino/commit/65a739a859fa8b98e755f23f2b9c8010d25ca1e2) [Matter examples](https://github.com/SiliconLabs/arduino/tree/main/libraries/Matter/examples)

![image](https://github.com/SiliconLabs/arduino/assets/938089/1d8eb419-9c48-4401-97de-95166876fb16)

**Comment by James-Smart** [comment]
Hi wanted to ask about this as well? How far off do you think it is? Deciding if its worth forking and adding. Cheers

**Comment by lboue** [comment]
> Hi wanted to ask about this as well? How far off do you think it is? Deciding if its worth forking and adding. Cheers

@James-Smart I think you can make a fork because it takes several months between each new version.

**Comment by James-Smart** [comment]
Excellent, thanks for the info

**Comment by lboue** [comment]
Hello @silabs-bozont 
Any news about the next release?

**Comment by silabs-bozont** [comment]
Hello @ruddycanuck,
Matter Door Lock is now available in 2.1.0.
See: https://github.com/SiliconLabs/arduino/blob/main/libraries/Matter/examples/matter_door_lock/matter_door_lock.ino
