### ISSUE TITLE
Arduino board installation problem

### ISSUE THREAD

**Issue by momososo** [SiliconLabs/arduino#2]
It says I'm missing some tools.
I'm using win10 and Arduino1.8.19
![2024-01-13 23 42 41](https://github.com/SiliconLabs/arduino/assets/11486286/5d694164-87e6-466b-91fd-99336fe24066)

**Comment by silabs-bozont** [comment]
Hi momososo,
The core only supports the newer 2.x Arduino IDEs - the legacy 1.x versions (including yours) are not supported.
Grab the latest version (2.2.1 as of now) from https://www.arduino.cc/en/software and install the core with that.
I'll add a note about this to the readme in the future - sorry for the inconvenience.
