### ISSUE TITLE
DeviceCommissioned when it isn't

### ISSUE THREAD

**Issue by TomInIowa** [SiliconLabs/arduino#26]
I am using  Apple HomeKit.
Adding to HomeKit works 

If for some reason  (added another matter temperature sensor). I **remove** the matter device from Apple HomeKit,
**the sketch code thinks it is still commissioned**...

To add the board back to Apple HomeKit again, I have to flash the board using the commander app

Now I can add the board to Apple HomeKit.  (again)

Something to fix in the matter code update??

**Comment by silabs-bozont** [comment]
Hi,
Yes, this can happen sometimes that the Matter credentials don't get erased from the device when unpairing - usually a device erase will solve it. The next version will have the erase option in the Arduino IDE, so it'll make it easier.
The credentials not getting erased usually happen for the following reasons:
- You remove the device from HomeKit when it's offline
- The device is reflashed/reset too early after being removed, so the credential purging can't finish
The next version will also come with an updated Matter SDK so it hopefully improves things in this regard as well.
