### ISSUE TITLE
[Feature Request] [Matter] Window Covering Support

### ISSUE THREAD

**Issue by Callum6677** [SiliconLabs/arduino#29]
I have a project which with the current list of clusters supported in matter would be best represented as a window closure setting a position on the lift control. Therefore thought I'd throw the feature request out.

(I do have shorter term workarounds)

**Comment by silabs-bozont** [comment]
Hi!
Matter Window Covering support is on the roadmap and is under implementation right now. If we're fast enough it'll make the next release in about 3 weeks.

**Comment by silabs-bozont** [comment]
It's now available in 2.0.0
