### ISSUE TITLE
README incorrectly specifies location to add repo's URL

### ISSUE THREAD

**Issue by ericwertz** [SiliconLabs/arduino#30]
In the README, in the Installation section, it says to go to "Settings" to splice-in the URL for the SiLabs repo to fetch from.  It should direct the user to "File->Preferences" within the Arduino IDE instead.

**Comment by silabs-bozont** [comment]
Hi,
Thanks for the heads up! Looks like it's different on each OS.
Mine looks like this:
<img width="273" alt="image" src="https://github.com/SiliconLabs/arduino/assets/124884281/7a3f99b9-b904-4cdb-9ea0-d0fd9f87689f">
Will update the readme to reflect all platforms correctly.

**Comment by ericwertz** [comment]
Yes.  I have bad karma, so I'm using Windows.  Didn't think to specify that.  Regards.

________________________________

**Comment by silabs-bozont** [comment]
No worries, Windows is not bad karma, it's totally fine :)

**Comment by silabs-bozont** [comment]
Updated readme in 2.0.0
