### ISSUE TITLE
How to reset/remove Matter commisioning

### ISSUE THREAD

**Issue by sammachin** [SiliconLabs/arduino#34]
Hi,
Is there a method in the Matter library to remove all the fabrics from the device and reset to the initial pairing state?
Couldn't see anything in the docs, an reflashing still finds the stored fabrics.

**Comment by silabs-bozont** [comment]
Hi sammachin,

The easiest method is with a chip erase - the current version of the core doesn't give you the option to erase from the Arduino IDE - but the next release will introduce the option.
Until then - you can erase you chip with [Simplicity Commander](https://community.silabs.com/s/article/simplicity-commander?language=en_US) or [Studio](https://www.silabs.com/developers/simplicity-studio) if you have them installed.
Your Arduino Core installation also comes bundled with Simplicity Commander - you can find it in the [Arduino15](https://support.arduino.cc/hc/en-us/articles/360018448279-Open-the-Arduino15-folder) folder at `Arduino15/packages/SiliconLabs/tools/simplicitycommander`. It's a GUI tool, just launch the executable.

You could also try calling `nvm3_eraseAll(nvm3_defaultHandle);` to erase the NVM contents.

Let me know if these worked for you!

**Comment by sammachin** [comment]
Hi,
Thanks for that, calling `nvm3_eraseAll(nvm3_defaultHandle);` worked for me.
