### ISSUE TITLE
Nothing happening here!

### ISSUE THREAD

**Issue by Travelbits** [SiliconLabs/arduino#37]
Hello All,

3 months ago the version 1.0.0 has been dropped at Github. Since then not much is happening at Github. I got some examples workings Silicon Labs xG24 exlorer kit boards. Today I received the Sparkfun Thingsplus Matter boards. I would love to go forward!!!!

But the https://siliconlabs.github.io/arduino/package_arduinosilabs_index.json link only gives me acces to 1.0.0.

At the https://docs.arduino.cc/tutorials/nano-matter/user-manual/ I can se that there is already a version 1.1.2.

Al I can read here is wait! But why? An open source project who is death for 3 months is not a great start. And this shows to me that You don’t share code at all.

So is this a real open source project? Or -in name only- for messages in the press who are nice for shareholders, not for makers.

Bye,
![Screenshot 2024-04-04 at 16 27 00](https://github.com/SiliconLabs/arduino/assets/63205663/eaca0575-b2a8-4922-9c27-030ef64045cc)

Guus

**Comment by lboue** [comment]
Version 1.0 was released in January and nothing has happened since. When SL will release the update the Arduino Matter?

I check Mouser and [Arduino Nano Matter](https://store.arduino.cc/pages/nano-matter) is expected 25-Jul-24. Why announce so far in advance?
