### ISSUE TITLE
declaration of delay() is not compatible with C language

### ISSUE THREAD

**Issue by lyusupov** [SiliconLabs/arduino#39]
**Core version**: 1.0.0
**Variant**:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    BGM220 Explorer Kit

Let's take this simple sketch and built it for BGM220 Explorer Kit target:

```
$ ls delay_test/
delay_test_c.c  delay_test.ino

$ cat delay_test/delay_test.ino

extern "C" void my_func();

void setup()
{
  delay(10);

  my_func();
}

void loop() { }

$ cat delay_test/delay_test_c.c

void my_func()
{
  delay(10);
}
```

Build of this sketch gives a linker failure

```
$ export BOARD=SiliconLabs:silabs:bgm220explorerkit

$ arduino-cli  compile -v --build-path=/tmp/arduino -b "$BOARD" delay_test

< ... skipped ... >

/home/codespace/.arduino15/packages/SiliconLabs/tools/gcc-arm-none-eabi/12.2.rel1/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: /tmp/arduino/sketch/delay_test_c.c.o: in function `my_func':
/workspaces/codespaces-blank/C6/delay_test/delay_test_c.c:3: undefined reference to `delay'
collect2: error: ld returned 1 exit status


Used platform      Version Path
SiliconLabs:silabs 1.0.0   /home/codespace/.arduino15/packages/SiliconLabs/hardware/silabs/1.0.0
```

We can see that declaration of `delay()` is not compatible with GNU-C language:
https://github.com/SiliconLabs/arduino/blob/main/cores/silabs/wiring.h#L74

When `delay()` function declaration is this one:

```
#ifdef __cplusplus
extern "C"{
#endif

void delay(uint32_t ms);

#ifdef __cplusplus
} // extern "C"
#endif
```

\- the build of this sketch is doing good.

It makes sense to consider update declaration of other Arduino functions compatible with C language like ArduinoCore-API does:
https://github.com/arduino/ArduinoCore-API/blob/master/api/Common.h

**Comment by silabs-bozont** [comment]
Hello lyusupov,
Thank you very much for bringing this to our attention. The next release is going to be based on the ArduinoCore-API, so this issue will be resolved.
