### ISSUE TITLE
Issue while burning the bootloaded

### ISSUE THREAD

**Issue by naveenneog** [SiliconLabs/arduino#5]
Hi,

I have the xG24 Explorer kit, I am trying to burn one example code into the kit but facing multiple issues.

1. Not able to burn the Bootloader 
![image](https://github.com/SiliconLabs/arduino/assets/40742835/4788638d-4980-4deb-a1cd-ba3cf43dd1a4)

Config 
<img width="309" alt="image" src="https://github.com/SiliconLabs/arduino/assets/40742835/6b63c1a5-29ef-41ab-8555-c9d9648310b0">

debug_custom.json contents 

`{
    "servertype": "jlink",
    "device": "EFR32MG24B210F1536IM48",
    "interface": "SWD",
    "serverpath": "C:\Program Files\SEGGER\JLink_V794e\JLinkGDBServerCL"
}`

Please help me to try the examples

**Comment by silabs-bozont** [comment]
Hi naveenneog,
It seems like Commander is unable to find your connected board. Make sure it's properly connected and the blue power LED is on.
The other common issue that can cause this is that you don't have the [J-Link Software and Documentation pack](https://www.segger.com/downloads/jlink/) installed. This contains the necessary drivers for flashing.
Please install it if you haven't already and let me know if it solves your issue!
The debugging configuration is not needed for flashing, you should be able to flash your device without creating the `debug_custom.json` file.
