### ISSUE TITLE
[bug] SpeedMax attribute missing for Fan device type

### ISSUE THREAD

**Issue by lboue** [SiliconLabs/arduino#67]
### Hardware

Silicon Labs xG24 Explorer Kit

### Core version

2.0.0

### Arduino IDE version

2.3.2

### Operating system

Windows 11

### Radio stack variant

Matter

### OpenThread Border Router device (if using Matter)

Apple TV 4K

### Issue description
The Matter specifications indicate that this attribute is mandatory but `SpeedMax` attribute missing for Fan device type.

**Matter-1.3-Application-Cluster-Specification.pdf page 306**

> 4.4.6.5. SpeedMax Attribute
>  This attribute SHALL indicate that the fan has one speed (value of 1) or the maximum speed, if the
>  fan is capable of multiple speeds.

I don't find SpeedMax Attribute in MatterFan.cpp:

https://github.com/SiliconLabs/arduino/blob/65a739a859fa8b98e755f23f2b9c8010d25ca1e2/libraries/Matter/src/MatterFan.cpp#L36-L44

### Minimal reproducer code

[matter_fan.ino](https://github.com/SiliconLabs/arduino/blob/main/libraries/Matter/examples/matter_fan/matter_fan.ino)

**Comment by lboue** [comment]
Check my PR #68 for this.

**Comment by silabs-bozont** [comment]
Hello @lboue,
Thank you for the finding and the PR. Unfortunately we don't have the community contributions set up yet - is it okay with you if I fix it in the upstream without your PR?

**Comment by lboue** [comment]
Yes, no problem with that

**Comment by lboue** [comment]
Thanks @silabs-bozont for this fix.
