### ISSUE TITLE
[request] Publish Matter temperature sensor value only when the value has changed

### ISSUE THREAD

**Issue by lboue** [SiliconLabs/arduino#69]
### Publish Matter temperature sensor value when only when the value has changed

Is there a way to publish Matter temperature sensor value only when only when the value has changed in the [Matter temperature sensor example](https://github.com/SiliconLabs/arduino/blob/main/libraries/Matter/examples/matter_temp_sensor/matter_temp_sensor.ino)?
Otherwise, it clogs up the Thread network unnecessarily by sending messages every 2 sec, or blocks the loop with the `sleep` method.

Regards

**Comment by silabs-bozont** [comment]
Hello @lboue,
Device change callbacks are now available with 2.1.0.
See: https://github.com/SiliconLabs/arduino/blob/main/libraries/Matter/examples/matter_lightbulb_callback/matter_lightbulb_callback.ino

**Comment by lboue** [comment]
Thanks @silabs-bozont
