### ISSUE TITLE
[request] getOnboardingQRCodeUrl() with leading `MT:` instead of `MT%3A`. 

### ISSUE THREAD

**Issue by rei-vilo** [SiliconLabs/arduino#70]
### Summary

Is there a dedicated function to get the QR-code with leading `MT:` instead of `MT%3A`. 

Currently, `getOnboardingQRCodeUrl()` requires some added code.

```cpp
    // Get code URL
    // Remove http address
    char * buffer = strstr(Matter.getOnboardingQRCodeUrl().c_str(), "MT%3A") + 5 - 3;

    // Replace MT%3A by MT:
    buffer[0] = 'M';
    buffer[1] = 'T';
    buffer[2] = ':';

    displayQR(buffer);
 ```

Thank you!

**Comment by silabs-bozont** [comment]
Hello @rei-vilo,
The next version will have an API for getting the onboarding payload - which can be used as-is for QR code generation.

**Comment by silabs-bozont** [comment]
Hello @rei-vilo,
In the new 2.1.0 release you can call `Matter.getOnboardingQRCodePayload();` to get the raw onboarding payload.
