### ISSUE TITLE
[bug] examples contain classic race between ISR and main thread

### ISSUE THREAD

**Issue by ericwertz** [SiliconLabs/arduino#74]
### Hardware

xG2x dev kits

### Core version

2.x

### Arduino IDE version

2.x

### Operating system

any

### Radio stack variant

BLE

### Issue description

ble_blinky and ble_hid_keyboard examples both contain the data-sharing-between-ISR-and-main bug where the shared data isn't declared volatile.  The code will only work as long as the optimizer is turned down/off and the globals' re-loads into registers aren't optimized away.

**Comment by silabs-bozont** [comment]
Hello @ericwertz - please fill in the missing parts of the issue template - especially the title.
Thank you!

**Comment by silabs-bozont** [comment]
Hello @ericwertz,
It has been fixed in 2.1.0 - thank you for the report!
