### ISSUE TITLE
[request] watchdog (reset) function is missing in the API

### ISSUE THREAD

**Issue by lyusupov** [SiliconLabs/arduino#83]
### Hardware

BGM220

### Core version

2.1.0

### Arduino IDE version

any

### Operating system

any

### Radio stack variant

No radio

### OpenThread Border Router device (if using Matter)

none

### Issue description

Current version of the API does not provide an interface that would allow to:
- init hardware watchdog timer
- reset hardware watchdog timer counter
- stop (de-init) hardware watchdog timer

<img width="605" alt="image" src="https://github.com/user-attachments/assets/e2078e7c-1389-4350-aeba-b15e6db6e6f0">

One can consider **Adafruit SleepyDog** library as an example of the watchdog API:
https://github.com/adafruit/Adafruit_SleepyDog

**Comment by leonardocavagnis** [comment]
Hello @lyusupov,
Thanks for the suggestion. Watchdog feature will be added in the next release.

**Comment by lyusupov** [comment]
https://github.com/SiliconLabs/arduino/blob/main/libraries/WatchdogTimer/readme.md

https://github.com/SiliconLabs/arduino/releases/tag/2.2.0
