### ISSUE TITLE
How to erase board flash memory

### ISSUE THREAD

**Issue by lboue** [SiliconLabs/arduino#9]
Hello,

I would like to erase my _Sparkfun ThingPlus Matter_ board flash memory.
I can't find how to do it in the README page. Could you tell me how?

Actually when I flash and run [matter_temp_sensor.ino](https://github.com/SiliconLabs/arduino/blob/main/libraries/Matter/examples/matter_temp_sensor/matter_temp_sensor.ino) the device is already commissioned and I can't reset it.
```
20:20:55.466 -> Matter flow sensor
20:20:55.855 -> Waiting for network connection...
20:20:56.040 -> Device connected
20:21:05.796 -> Current flow: 0.00 m3/h
20:21:15.799 -> Current flow: 0.50 m3/h
20:21:25.794 -> Current flow: 1.00 m3/h
20:21:35.841 -> Current flow: 1.50 m3/h
20:21:45.819 -> Current flow: 2.00 m3/h
20:21:55.845 -> Current flow: 2.50 m3/h
20:22:05.831 -> Current flow: 3.00 m3/h
```

Regards

**Comment by silabs-bozont** [comment]
Hi!
Thanks for your suggestion @Brezensalzer - that's what I was also about to suggest.
The next version will have this hooked in in the `platform.txt` so burning the bootloader from the Arduino IDE will also do an erase, also it'll be able to safely distinguish between the connected boards. Leaving this out was an oversight on our part.
You can also execute the built-in commander without parameters - then it'll open up a GUI and you can more safely erase it from there.
If you have a hard time finding the built-in commander, then you can also download a standalone version: https://www.silabs.com/developers/simplicity-studio#commander
Let me know if these tips worked for you!
