### ISSUE TITLE
[request] 'analogReadResolution' was not declared in this scope; 

### ISSUE THREAD

**Issue by runger1101001** [SiliconLabs/arduino#94]
### Summary

Please implement analogReadResolution(), as the EFR32 supports different resolutions depending on speed mode and oversampling configuration.
Even if you fix it at 12 bits, it would be nice to provide this method for compatibility with the other Ardunio cores that have it.

**Comment by leonardocavagnis** [comment]
Dear @runger1101001,
Thanks for reporting. We'll add this fix in the next release.

**Comment by runger1101001** [comment]
Thank you :-)
