### ISSUE TITLE
[request] Support for Seeed Xiao MG24

### ISSUE THREAD

**Issue by rei-vilo** [SiliconLabs/arduino#98]
### Summary

Seeed has announced the release of the [Xiao MG24](https://www.seeedstudio.com/Seeed-Studio-XIAO-MG24-p-6247.html) and the [Xiao MG24 Sense](https://www.seeedstudio.com/Seeed-XIAO-MG24-Sense-p-6248.html). 

Do you plan to support those two new boards?

Thank you!

**Comment by lboue** [comment]
@rei-vilo The procedure can be found here, but is not applicable as the new version has not yet been published:
 - [Add the XIAO MG24 Board](https://wiki.seeedstudio.com/xiao_mg24_getting_started/#add-board)

**Comment by rei-vilo** [comment]
Thank you! 

Is there an ETA for the new version?

**Comment by loozhengyuan** [comment]
@rei-vilo From Seeed Studio's Discord, it appears that they have plans to publish before they start shipping the new boards (estimated end-Nov).

**Comment by lboue** [comment]
@rei-vilo 
Check this: https://github.com/SiliconLabs/arduino/releases/tag/2.2.0

**Comment by rei-vilo** [comment]
Thank you, case closed!
